### ISSUE TITLE
Why Nuxt?

### ISSUE THREAD

**Issue by robertpro** [juanjcardona13/DjangoNuxt#1]
I am wondering what is the use of Nuxt in this project, I was expecting to use Django as a Nuxt replacement, maybe this does not make sense since I have never used Nuxt and I am just learning frontend/webpack, etc.

**Comment by juanjcardona13** [comment]
The idea is to achieve something like what they achieved in blogs that leave reference, to use the best of both worlds

**Comment by robertpro** [comment]
Do you have any contact method? I would chat with you about your idea

**Comment by juanjcardona13** [comment]
E-mail: juanjcardona13@gmail.com
